config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  resources :images do
    get 'search', on: :collection, as: :search
  end
end

app/models/application_record.rb
# frozen_string_literal: true
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/searchable.rb
module Searchable
    extend ActiveSupport::Concern
  
    included do
      include Elasticsearch::Model
      include Elasticsearch::Model::Callbacks
    end
  end

app/models/image.rb
# frozen_string_literal: true
require 'fuzzystringmatch'

class Image < ApplicationRecord
  has_one_attached(:file)

  validates :title, presence: true, length: { minimum: 3, maximum: 30 }
  validates :file, presence: true

  validate :file_smallerthan_2m
  validate :file_correct_mimetype

  ACCEPTED_MIME_TYPE = Set['image/png', 'image/jpeg']

  def self.search(query)
    results = []

    # GC, dont fail me now
    @fuzzymatcher = FuzzyStringMatch::JaroWinkler.create(:native)

    # this probably wont scale
    Image.all.each do |image|
      results.push(image) if @fuzzymatcher.getDistance(image.title, query) > 0.4 # 0.4 should be a var
    end
    results
  end

  # not a good name
  def get_size(size)
    size.to_i != 0 ? file.variant(resize_to_fit: [size, size]) : file
  end

  private

  def file_smallerthan_2m
    return unless file.attached?
    if file.byte_size > 2.megabytes
      errors.add(:file, 'size larger than 2M maximum')
    end
  end

  def file_correct_mimetype
    return unless file.attached?
    unless ACCEPTED_MIME_TYPE.include?(file.content_type)
      errors.add(:file, "incorrect mime type: #{file.content_type}")
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true
class ApplicationController < ActionController::API
end

app/controllers/images_controller.rb
# frozen_string_literal: true
class ImagesController < ApplicationController
  def index
    @images = Image.all
    render(json: @images)
  end

  def show
    @image = Image.find(params[:id])
    redirect_to(url_for(@image.get_size(params[:size])))
  end

  def create
    @image = Image.new(image_params)
    @image.save ? render(json: @image) : render(json: @image.errors)
  end

  def destroy
    @image = Image.find(params[:id])
    @image.file.purge_later
    @image.delete
    render(json: @image)
  end

  def search
    render(json: Image.search(params[:query]))
  end

  private

  def image_params
    params.require(:file)
    params.require(:title)
    params.permit(:file, :title)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def search
        if params[:query].blank?
          @results = []
        else
          @results = Elasticsearch::Model
                       .search(params[:query])
                       .results.as_json
                       .group_by { |result| result['_index'] }
        end
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/images/index.html.erb
<%= link_to 'Add Image', new_image_path %>
<%= link_to 'Search', search_images_path %>
<% @images.each do |image| %>
    <p><%= image.title %></p>
    <%= link_to (image_tag image.file.variant(resize_to_limit: [500, 500] ) if image.file.attached?), image %>
<% end %>

app/views/images/new.html.erb
<%= form_with model: @image do |form| %>

    <%= form.label :title %>
    <%= form.text_field :title %>
    <% @image.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>

    <%= form.label :file %>
    <%= form.file_field :file %>
    <% @image.errors.full_messages_for(:file).each do |message| %>
      <div><%= message %></div>
    <% end %>

    <%= form.submit %>

    
<% end %>

app/views/images/search.html.erb
<h1>Image Search</h1>
<%= link_to 'Home', root_path%>
<%= form_with url: search_images_path, method: :get do |form| %>
    <%= form.label :query %>
    <%= form.text_field :query %>

    <%= form.submit 'search' %>
<% end %>

<% if @results %>
    <% @results.each do |result| %>
        <p><%= result.title %></p>
        <%= link_to (image_tag result.file.variant(resize_to_limit: [500, 500] ) if result.file.attached?), result %>
    <% end %>
<% else %>
    <h2>No results</h2>
<% end %>

app/views/images/show.html.erb
<h2> <%= @image.title %></h2>

<div>
<%= link_to "Home", root_path %>
</div>

<div>
<%= link_to "Destroy", image_path(@image), method: :delete, data: { confirm: "Are you sure you want to delete this image?" } %>
</div>

<div>
<%= image_tag @image.file.variant(resize_to_limit: [500, 500] ) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImgRepo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/search/search.html.erb
<h1>Image Search</h1>

<%= form_for search_path, method: :get do |form| %>
  <p>
    <%= form.label :query %>
    <%= text_field_tag :query, params[:query] %>
    <%= submit_tag "Search", name: nil %>
  </p>
<% end %>

<% if params[:query] && @results.blank? %>
  <p>No results found for <%= params[:query] %></p>
<% end %>

<% @results.each do |model, records| %>
  <h3><%= model.titleize %></h3>

  <ul>
    <% records.each do |record| %>
      <% record_link = "#{model}/#{record['_id']}" %>
      <li>
        <%puts "--------\n", record["_source"]["title"], "\n--------" %>
        <%= link_to ("#{record["_source"]["title"]} #{record_link}"), record_link %>
      </li>
    <% end %>
  </ul>

<% end %>